version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    build:
      context: ./dockerfiles
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - S3_BUCKET_NAME=my-bucket
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "8080:8080"
    command: /entrypoint.sh webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  airflow-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/s3/${S3_BUCKET_NAME}/airflow-db-bucket
  airflow-logs-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/s3/${S3_BUCKET_NAME}/airflow-logs-bucket
  airflow-plugins-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/s3/${S3_BUCKET_NAME}/airflow-plugins-bucket

networks:
  airflow-network:
    name: airflow-network
